version: 2.1
orbs:
  slack: circleci/slack@0.1.0
  heroku: circleci/heroku@0.0.1
  lloydwework: lloydwework/hello@dev:first
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "A first hello"
      - run: ls -a
      - run: sleep 25
      - lloydwework/hello:
          username: "Lloyd"
workflows:
  version: 2
  one_and_two:
    jobs:
      - build
